description: Bare bones starter template for Eleventy and Decap CMS using
  Netlify for hosting and auth (Netlify Identity)
url: https://github.com/tjgilpin/11ty-decap-netlify
name: Starter template for Eleventy and Decap CMS
locale: en_GB
title: Starter template for Eleventy and Decap CMS
image: /static/img/496404201.jpg
width: 1280
height: 630
alt: Screenshot of website at https://github.com/tjgilpin/11ty-decap-netlify
