logo: /static/img/rada-logo.png
description: RADA Studija - Vieta, kur radīt, mācīties un just.
url: https://github.com/tjgilpin/11ty-decap-netlify
name: Starter template for Eleventy and Decap CMS
locale: en_GB
title: Starter template for Eleventy and Decap CMS
image: /static/img/496404201.jpg
width: 1280
height: 630
alt: Screenshot of website at https://github.com/tjgilpin/11ty-decap-netlify
posts: Articles
postsorder: 100
