backend:
  name: git-gateway
  branch: master
media_folder: "src/static/img"
public_folder: "/static/img"
local_backend: true

collections:
  # RESTORED: The 'Pages' collection
  # - label: "Pages"
  #   name: "pages"
  #   folder: "src/pages"
  #   create: true
  #   editor:
  #     preview: false    
  #   fields:
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Author", name: "author", widget: "string" }
  #     - { label: "Body", name: "body", widget: "markdown" }
  #     - { label: "Remove from Navigation", name: "eleventyExcludeFromCollections", widget: "boolean", default: false }
  #     - { label: "Navigation Order", name: "order", widget: "number", default: 0 }

  # RESTORED: The 'Posts' collection for your blog
  - label: "Events"
    name: "events"
    folder: "src/events" # Folder where event markdown files will be stored
    create: true
    editor:
      preview: false # Keep preview off for now
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Event Date", name: "date", widget: "datetime" }
      - { label: "Short Description (for card)", name: "description", widget: "string" }
      # Optional: Add an image field if needed for the event card or page
      # - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Event Details (Main Content)", name: "body", widget: "markdown" }
      # Optional: Add navigation order if needed, similar to pages
      # - { label: "Navigation Order", name: "order", widget: "number", default: 0 }
  # UPDATED: The 'Settings' collection with dynamic homepage sections
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Site Settings & Homepage"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          # --- General Site Settings ---
          - { label: "Site Name", name: "name", widget: "string" }
          - { label: "Site URL", name: "url", widget: "string" }
          - { label: "Logo", name: "logo", widget: "image", allow_multiple: false }
          - { label: "Default SEO Title", name: "title", widget: "string" }
          - { label: "Default SEO Description", name: "description", widget: "string" }
          - { label: "Default SEO Image", name: "image", widget: "image", allow_multiple: false }
          
          # --- Intro Section (Static) ---
          - label: "Intro Section"
            name: "intro_section"
            widget: "object"
            fields:
              - { label: "Subtitle", name: "subtitle", widget: "string" }
              - { label: "Secondary Image", name: "secondary_image", widget: "image" }

          # --- Main Content Sections (Dynamic List) ---
          - label: "Homepage Content Sections"
            name: "main_sections"
            widget: "list"
            summary: "{{fields.title}} | Style: {{fields.layout_style}}"
            collapsed: false
            fields:
              - { label: "Section Title", name: "title", widget: "string" }
              - label: "Layout Style"
                name: "layout_style"
                widget: "select"
                options:
                  - { label: "Alternating Left/Right Image", value: "default" }
                  - { label: "Full Green Overlay", value: "full_overlay" }
                default: "default"
              - { label: "Background Image", name: "background_image", widget: "image" }
              - { label: "Description", name: "description", widget: "markdown" }
              - { label: "Show 'Join Us' Button?", name: "show_join_button", widget: "boolean", default: false }
              - label: "Join Button Details"
                name: "join_button"
                widget: "object"
                required: false
                fields:
                  - { label: "Button Text", name: "text", widget: "string", default: "Pievienojies RADA" }
                  - { label: "Button URL", name: "url", widget: "string", default: "#" }
              - label: "Reference Links"
                name: "reference_links"
                widget: "list"
                required: false
                collapsed: true
                summary: "{{fields.text}}"
                fields:
                  - { label: "Link Text", name: "text", widget: "string" }
                  - { label: "Link URL", name: "url", widget: "string" }

      # Footer Links collection (unchanged)
      - label: "Footer Links"
        name: "footerlinks"
        file: "src/_data/footerlinks.yaml"
        fields:
          - label: Footer Links
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: desc, widget: string, required: false }
              - { label: Icon, name: icon, widget: string, hint: "Enter a Font Awesome class, e.g., 'fab fa-instagram' or 'fas fa-envelope'" }
